// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: events.sql

package repo

import (
	"context"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (user_id, application_id, type, payload_json)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, application_id, type, payload_json, created_at
`

type CreateEventParams struct {
	UserID        *int64 `json:"user_id"`
	ApplicationID *int64 `json:"application_id"`
	Type          string `json:"type"`
	PayloadJson   []byte `json:"payload_json"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.UserID,
		arg.ApplicationID,
		arg.Type,
		arg.PayloadJson,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicationID,
		&i.Type,
		&i.PayloadJson,
		&i.CreatedAt,
	)
	return i, err
}
