// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID           int64              `json:"id"`
	JobID        int64              `json:"job_id"`
	UserID       int64              `json:"user_id"`
	Status       string             `json:"status"`
	Notes        *string            `json:"notes"`
	NextActionAt pgtype.Timestamptz `json:"next_action_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Job struct {
	ID        int64              `json:"id"`
	OrgID     *int64             `json:"org_id"`
	Title     string             `json:"title"`
	Company   string             `json:"company"`
	Url       *string            `json:"url"`
	Location  *string            `json:"location"`
	Tags      []string           `json:"tags"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
